# -*- coding: utf-8 -*-
"""HousePricePrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/NeejiMed/de5a47a76e75ba396be42aa779fbc5d4/housepriceprediction.ipynb
"""
#import Libraries
import numpy as np # linear algebra
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import metrics

#import DataSet
df=pd.read_csv('/content/kc_house_data.csv')
df.head()

df.drop('id',  axis='columns', inplace=True)
df.drop('date',  axis='columns', inplace=True)
#df.drop('zipcode',  axis='columns', inplace=True)
df.drop('long',  axis='columns', inplace=True)
df.drop('lat',  axis='columns', inplace=True)
#df.drop('waterfront',  axis='columns', inplace=True)
#df.drop('view',  axis='columns', inplace=True)
#df.drop('yr_renovated',  axis='columns', inplace=True)
df.head()

df.head()

#data.plot.scatter(y='sqft_living',x='price')
x = df[['bedrooms','bathrooms','sqft_living','bathrooms','sqft_lot','floors','waterfront','view','condition','grade','sqft_above','sqft_basement','yr_built','yr_renovated','zipcode','sqft_living15','sqft_lot15']]
#x=data.values[:,np.newaxis]
y=df["price"].values

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.35,random_state=40) #splitting data with test size of 35%

model=LinearRegression()   #build linear regression model
model.fit(x_train,y_train)  #fitting the training data
predicted=model.predict(x_test) #testing our model’s performance


print("MSE", mean_squared_error(y_test,predicted))
print("R squared", metrics.r2_score(y_test,predicted))

print(model.intercept_)
coeff_df=pd.DataFrame(model.coef_,x.columns,columns=['Coeff'])
coeff_df

predictions = model.predict(x_test)
plt.scatter(y_test,predictions)

sns.displot((y_test-predictions),bins=50)